@echo off
REM ==============================================================================
REM LicenseFlow Self-Hosted 1-Click Automated Setup Wizard (Windows)
REM ==============================================================================
setlocal enabledelayedexpansion

echo ================================================================
echo    LicenseFlow Self-Hosted Setup Wizard (Windows)
echo ================================================================
echo.

REM 1. Check Prerequisites
echo [1/3] Checking Docker...
docker --version >nul 2>&1
if %errorlevel% neq 0 (
    echo [ERROR] Docker is not installed or not in PATH.
    echo Please install Docker Desktop from https://www.docker.com/products/docker-desktop/
    pause
    exit /b 1
)

REM 2. Generate Random Secrets via PowerShell
echo [2/3] Generating secure cryptographic keys...
for /f "delims=" %%i in ('powershell -Command "[Convert]::ToBase64String((1..32 | ForEach-Object { Get-Random -Minimum 0 -Maximum 256 })) -replace '[^a-zA-Z0-9]','' | Select-Object -First 32"') do set JWT_SECRET=%%i
for /f "delims=" %%i in ('powershell -Command "[Convert]::ToBase64String((1..32 | ForEach-Object { Get-Random -Minimum 0 -Maximum 256 })) -replace '[^a-zA-Z0-9]','' | Select-Object -First 32"') do set MASTER_KEY=%%i
for /f "delims=" %%i in ('powershell -Command "[Convert]::ToBase64String((1..32 | ForEach-Object { Get-Random -Minimum 0 -Maximum 256 })) -replace '[^a-zA-Z0-9]','' | Select-Object -First 32"') do set DB_PASS=%%i
for /f "delims=" %%i in ('powershell -Command "[Convert]::ToBase64String((1..32 | ForEach-Object { Get-Random -Minimum 0 -Maximum 256 })) -replace '[^a-zA-Z0-9]','' | Select-Object -First 32"') do set MINIO_PASS=%%i

set ENV_FILE=self-hosted\docker\.env
if not exist self-hosted\docker mkdir self-hosted\docker

(
echo # Auto-generated by LicenseFlow Setup Wizard on %date% %time%
echo POSTGRES_USER=licenseflow
echo POSTGRES_PASSWORD=%DB_PASS%
echo POSTGRES_DB=licenseflow
echo DATABASE_URL=postgresql://licenseflow:%DB_PASS%@postgres:5432/licenseflow
echo JWT_SECRET=%JWT_SECRET%
echo MASTER_ENCRYPTION_KEY=%MASTER_KEY%
echo APP_URL=http://localhost:3000
echo API_URL=http://localhost:8080
echo MINIO_ROOT_USER=admin
echo MINIO_ROOT_PASSWORD=%MINIO_PASS%
echo RUN_MIGRATIONS=true
) > %ENV_FILE%

echo [OK] Secrets generated and written to %ENV_FILE%
echo.

REM 3. Start Containers
echo [3/3] Starting Docker Compose stack...
cd self-hosted\docker
docker compose up -d

echo.
echo ================================================================
echo    LicenseFlow Self-Hosted is now running!
echo ================================================================
echo Dashboard UI:   http://localhost:3000
echo API Gateway:    http://localhost:8080
echo MinIO Console:  http://localhost:9001
echo ================================================================
echo.
pause
