#!/usr/bin/env bash
# ==============================================================================
# LicenseFlow Self-Hosted 1-Click Automated Setup Wizard
# ==============================================================================
set -euo pipefail

BOLD='\033[1m'
GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

echo -e "${CYAN}${BOLD}"
cat << "EOF"
  _      _                          ______ _                 
 | |    (_)                        |  ____| |                
 | |     _  ___ ___ _ __  ___  ___ | |__  | | _____      __  
 | |    | |/ __/ _ \ '_ \/ __|/ _ \|  __| | |/ _ \ \ /\ / /  
 | |____| | (_|  __/ | | \__ \  __/| |    | | (_) \ V  V /   
 |______|_|\___\___|_| |_|___/\___||_|    |_|\___/ \_/\_/    
                                                              
        Enterprise Licensing & Entitlement Data Plane         
                   Self-Hosted Setup Wizard                  
EOF
echo -e "${NC}"

# 1. Prerequisite Checks
echo -e "${BOLD}▶ Step 1: Checking prerequisites...${NC}"

if ! command -v docker &> /dev/null; then
    echo -e "${RED}❌ Docker is not installed. Please install Docker first: https://docs.docker.com/get-docker/${NC}"
    exit 1
fi

if ! docker compose version &> /dev/null && ! command -v docker-compose &> /dev/null; then
    echo -e "${RED}❌ Docker Compose is not installed.${NC}"
    exit 1
fi

echo -e "${GREEN}✓ Docker and Docker Compose detected.${NC}\n"

# 2. Generate Cryptographically Secure Secrets
echo -e "${BOLD}▶ Step 2: Generating high-entropy cryptographic keys...${NC}"

gen_secret() {
    if command -v openssl &> /dev/null; then
        openssl rand -base64 32 | tr -dc 'a-zA-Z0-9' | head -c 32
    else
        head -c 32 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 32
    fi
}

JWT_SECRET=$(gen_secret)
MASTER_KEY=$(gen_secret)
DB_PASS=$(gen_secret)
CRON_SECRET=$(gen_secret)
MINIO_PASS=$(gen_secret)

ENV_FILE="self-hosted/docker/.env"
mkdir -p self-hosted/docker

if [ -f "$ENV_FILE" ]; then
    echo -e "${YELLOW}⚠️  Existing .env file found at $ENV_FILE. Backing up to .env.bak...${NC}"
    cp "$ENV_FILE" "${ENV_FILE}.bak"
fi

cat > "$ENV_FILE" << EOF
# Auto-generated by LicenseFlow Setup Wizard on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Database Credentials
POSTGRES_USER=licenseflow
POSTGRES_PASSWORD=${DB_PASS}
POSTGRES_DB=licenseflow
DATABASE_URL=postgresql://licenseflow:${DB_PASS}@postgres:5432/licenseflow

# Cryptographic Keys
JWT_SECRET=${JWT_SECRET}
MASTER_ENCRYPTION_KEY=${MASTER_KEY}
CRON_SECRET=${CRON_SECRET}

# Application Endpoints
APP_URL=http://localhost:3000
API_URL=http://localhost:8080
VERSION=2.1.0

# Storage (MinIO)
MINIO_ROOT_USER=admin
MINIO_ROOT_PASSWORD=${MINIO_PASS}
STORAGE_ENDPOINT=http://minio:9000
STORAGE_BUCKET=artifacts
STORAGE_PUBLIC_URL=http://localhost:9000/artifacts

RUN_MIGRATIONS=true
EOF

echo -e "${GREEN}✓ Secrets generated and written to ${ENV_FILE}${NC}\n"

# 3. Boot Container Stack
echo -e "${BOLD}▶ Step 3: Starting LicenseFlow container stack...${NC}"
cd self-hosted/docker

if docker compose version &> /dev/null; then
    docker compose up -d --wait || docker compose up -d
else
    docker-compose up -d
fi

echo -e "${GREEN}✓ Container services started successfully.${NC}\n"

# 4. Completion Summary
echo -e "${CYAN}================================================================${NC}"
echo -e "${GREEN}${BOLD}🎉 LicenseFlow Self-Hosted Edition is now running!${NC}"
echo -e "${CYAN}================================================================${NC}"
echo -e "${BOLD}Dashboard UI:${NC}        http://localhost:3000"
echo -e "${BOLD}API Gateway:${NC}         http://localhost:8080"
echo -e "${BOLD}MinIO Console:${NC}       http://localhost:9001 (User: admin / Pass: ${MINIO_PASS})"
echo -e "${CYAN}================================================================${NC}"
echo -e "To view logs:         cd self-hosted/docker && docker compose logs -f"
echo -e "To stop services:     cd self-hosted/docker && docker compose down"
echo -e "Configuration:        ${ENV_FILE}"
echo -e "${CYAN}================================================================${NC}\n"
